# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4effaac8a6f31c8682cf6f80fe53016e446914e67b2f8699fcf5e13e51b157de0b00deb62e0d70ea0e47f774113c128032652216898fe73b5414fd93f5623f9f

test:
  secret_key_base: 6c4224114c08806ba9e5db31baa16f97cef8360743e3b1a81b6e794c38ac22b4e43e2310c36a8d31c12aa93eaaecc30787b6993eb07eaab3d11f3c49b7348c70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
